### ISSUE TITLE
__cache__/out路径中的.md文件，如何自动导入不同的法律效力位阶的文件夹？代码里面好像没有这个逻辑，手动复制粘贴吗？

### ISSUE THREAD

**Issue by mechigonft** [LawRefBook/Laws#11]
看了一下代码，只有remove的逻辑，是去【当前工作目录的上一级目录以及其子目录】检查是否有重复文件，有重复文件就从__cache__/out路径中删除重复文件，但是好像没有将非重复文件移动到对应的法律效力位阶文件夹的逻辑？

**Comment by mechigonft** [comment]
这个地方是bug啊，所有在__cache__/out路径中的文件是百分百会被删除啊，因为__cache__/out也在lookup = Path("../")的子目录中，所以在子目录中检查是否有重复文件时，就出现了自己检查自己的问题？这百分百检查到啊，百分百会被删除
file_path：
PosixPath('__cache__/out/互联网上网服务营业场所管理条例(2022-03-29).md')
file_path.name = '互联网上网服务营业场所管理条例(2022-03-29).md'
然后去检查：
检查结果是：
lookup_files：
[PosixPath('../Laws-master 4/__cache__/out/互联网上网服务营业场所管理条例(2022-03-29).md')]
可以看到，自己检查到了自己，所以一定会被删除，也就是说__cache__/out路径中的文件一定会被删除

**Comment by mechigonft** [comment]
这块是bug吗？还是作者的目的就是清空__cache__/out路径？如果是后者，完全没必要这么麻烦清空一个文件夹，我理解作者应该是做“增量”的操作吧，就是把重复文件删除，留下没重复的增量文件

那增量文件的后续处理呢？难道不是应该自动地将它们移动到对应的法律效力位阶文件夹中吗？

**Comment by RanKKI** [comment]
我这里很暴力的直接

`lookup_files = filter(lambda x: "scripts" not in x.parts, lookup_files)`

所有在 `scripts` 下的文件会被忽略掉, `__cache__` 在 `scripts` 下， 因此不受影响。

---

关于 `移动到对应的法律效力位阶文件夹`， 之前是有这部分逻辑。 但因为后续新出的法规并没有对应的 种类，例如：社会法，经济法。因此只能手动移入到对应的位置。

**Comment by mechigonft** [comment]
所以导致了百分百删除的情况

**Comment by mechigonft** [comment]
我知道了，是我工作路径的问题，我应该到scripts文件夹下再运行request.py

**Comment by mechigonft** [comment]
我运行python代码，并不会直接进入脚本所在的文件夹，而是会直接python+脚本所在绝对路径去执行了，此时__cache__就不会创建在scripts路径下，就会出现上述问题
