### ISSUE TITLE
建议增加消防法及消防相关法律法规

### ISSUE THREAD

**Issue by ljlog** [LawRefBook/Laws#13]
如题

**Comment by RanKKI** [comment]
《消防法》已经有了 在这个 [commit](https://github.com/LawRefBook/Laws/commit/ad3fc7a710153f0a72b1a600f57654aab9653c36) [消防法(2021-04-29).md
](https://github.com/LawRefBook/Laws/blob/master/%E8%A1%8C%E6%94%BF%E6%B3%95/%E6%B6%88%E9%98%B2%E6%B3%95(2021-04-29).md)
