### ISSUE TITLE
法律收集汇总信息

### ISSUE THREAD

**Issue by zmxccxy** [LawRefBook/Laws#14]
帮忙看看下面这个是不是本项目的？之前能看到这样的汇总信息，现在看不到了
<img width="361" alt="22f2b6c617fc316ffce6146badcd8cc2" src="https://github.com/LawRefBook/Laws/assets/150102974/d8588e68-3a7b-477d-b6f5-6dd159b13cbb">

**Comment by RanKKI** [comment]
在 https://lawrefbook.github.io/

目前看 似乎没啥问题？
