### ISSUE TITLE
法条有效性筛选

### ISSUE THREAD

**Issue by mechigonft** [LawRefBook/Laws#7]
你好，请问一下，代码筛选的法典实效性状态是【有效】+【已修改】吗，有些法，同时存在有效和已修改状态，会导致爬到两部同名法典
![海洋环境保护法](https://github.com/LawRefBook/Laws/assets/90537707/ddb984a4-4b27-4e8f-9e33-564b298b0e98)
同样的情况还有：反间谍法、体育法等。

**Comment by RanKKI** [comment]
这里没有做 filter，但 api 应该是有对应的配置；可以去数据库里做一次请求，看看用了哪个
