### ISSUE TITLE
http连接异常，超时，重试最大次数

### ISSUE THREAD

**Issue by mechigonft** [LawRefBook/Laws#8]
TimeoutError: [Errno 110] Connection timed out
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f86f5915d00>: Failed to establish a new connection: [Errno 110] Connection timed out
  File "/opt/conda/lib/python3.8/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='flk.npc.gov.cn', port=443): Max retries exceeded with url: /api/?xlwj=02&xlwj=03&xlwj=04&xlwj=05&xlwj=06&xlwj=07&xlwj=08&searchType=title%3Baccurate%3B1%2C3&sortTr=f_bbrq_s%3Bdesc&gbrqStart=&gbrqEnd=&sxrqStart=&sxrqEnd=&sort=true&page=1&size=10&_=1704176175335 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f86f5915d00>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by mechigonft** [comment]
将url直接贴到浏览器测试是可以的
![直接测试是可以的](https://github.com/LawRefBook/Laws/assets/90537707/0f019af0-0040-4706-aa2b-069132f049d0)

**Comment by RanKKI** [comment]
和 #9 可能是一样的问题，可能是 cli 走了 proxy ，但浏览器没用? 之类的
